# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BlAsbdB2xXTlf11mKhv2QoryCG9pzBqt
"""

import sys
!{sys.executable} -m pip install streamlit transformers
import streamlit as st
from transformers import pipeline

# Load pretrained model
generator = pipeline(
    "text-generation",
    model="google/flan-t5-large"
)

# Streamlit UI
st.set_page_config(page_title="International Marketing App")

st.title("🌍 International Business Marketing Prompt App")

product = st.text_input("Enter Product Name")

if st.button("Generate Marketing Content"):

    prompt = f"""
    Product Name: {product}

    Generate:
    1. Global Product Title
    2. Marketing Slogan
    3. Emotional Marketing Description
    4. Luxury Branding Description
    5. Social Media Advertising Description

    Make the content globally attractive and professional.
    """

    result = generator(
        prompt,
        max_length=300,
        do_sample=True,
        temperature=0.8
    )

    output = result[0]["generated_text"]

    st.subheader("Generated Marketing Content")
    st.write(output)